export type AddType = "EVENT" | "SERVICE" | "PRODUCT" | "PACKAGE" | "CLIENT"

const LOGIN_ACTION: string = "LOGIN";
const REGISTER_ACTION: string = "REGISTER";
const TOGGLE_LOGIN_VIEW_ACTION: string = "TOGGLE_LOGIN_VIEW";


export var ROOT_ACTION_CONSTANTS = {
    LOGIN: LOGIN_ACTION,
    REGISTER: REGISTER_ACTION,
    TOGGLE_LOGIN_VIEW: TOGGLE_LOGIN_VIEW_ACTION
}