export type AddType = "EVENT" | "SERVICE" | "PRODUCT" | "PACKAGE" | "CLIENT"

const LOGIN_ACTION: string = "LOGIN";
const REGISTER_ACTION: string = "REGISTER";
const TOGGLE_LOGIN_VIEW_ACTION: string = "TOGGLE_LOGIN_VIEW";


export let ROOT_ACTION_CONSTANTS = {
    LOGIN: LOGIN_ACTION,
    REGISTER: REGISTER_ACTION,
    TOGGLE_LOGIN_VIEW: TOGGLE_LOGIN_VIEW_ACTION
}

const LOAD_EVENT_ACTION = "LOAD_EVENT";
const LOAD_EVENT_DETAIL_ACTION = "LOAD_EVENT_DETAIL";
const CREATE_EVENT_ACTION = "CREATE_EVENT";
const EDIT_EVENT_ACTION = "EDIT_EVENT";
const DELETE_EVENT_ACTION = "DELETE_EVENT";
const CHANGE_FILTERING_METHOD_ACTION = "CHANGE_FILTERING_METHOD";
const CHANGE_SORTING_METHOD_ACTION = "CHANGE_SORTING_METHOD";
const CHANGE_START_DATE_RANGE_ACTION = "CHANGE_START_DATE_RANGE";
const CHANGE_END_DATE_RANGE_ACTION = "CHANGE_END_DATE_RANGE";
const TOGGLE_VIEW_ACTION = "TOGGLE_VIEW";

export let EVENT_VIEW_ACTION_CONSTANTS = {
    LOAD_EVENTS: LOAD_EVENT_ACTION,
    CHANGE_FILTERING_METHOD: CHANGE_FILTERING_METHOD_ACTION,
    CHANGE_SORTING_METHOD: CHANGE_SORTING_METHOD_ACTION,
    CHANGE_START_DATE_RANGE: CHANGE_START_DATE_RANGE_ACTION,
    CHANGE_END_DATE_RANGE: CHANGE_END_DATE_RANGE_ACTION,
    TOGGLE_VIEW: TOGGLE_VIEW_ACTION
};
export let EVENT_ACTION_CONSTANTS = {
    LOAD_EVENT_DETAIL: LOAD_EVENT_DETAIL_ACTION,
    CREATE_EVENT: CREATE_EVENT_ACTION,
    EDIT_EVENT: EDIT_EVENT_ACTION,
    DELETE_EVENT: DELETE_EVENT_ACTION
};