export type AddType = "EVENT" | "SERVICE" | "PRODUCT" | "PACKAGE" | "CLIENT"

const LOGIN_ACTION: string = "LOGIN";
const REGISTER_ACTION: string = "REGISTER";
const VIEW_LOGIN_ACTION: string = "VIEW_LOGIN";
const VIEW_REGISTRATION_ACTION: string = "VIEW_REGISTRATION";
export var ROOT_ACTION_CONSTANTS = {
    LOGIN: LOGIN_ACTION,
    REGISTER: REGISTER_ACTION,
    VIEW_LOGIN: VIEW_LOGIN_ACTION,
    VIEW_REGISTRATION: VIEW_REGISTRATION_ACTION
}